spring:
  application:
    name: api-gateway

server:
  port: 8090


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    app-name: api-gateway-service
    instance-id: ${spring.application.name}:${random.value}
